### PR TITLE
instruction & ta pictures layout fixed

### PR DESCRIPTION
**Pull request by armingh2000**
image

+: both instructors are shown
+: ta layout is fixed

### CODE REVIEW

**Comment by armingh2000** [comment]
https://armingh2000.github.io/ai99/
for a better view over the website

**Comment by armingh2000** [comment]
Course Instructor has changed to Course Instructor"s"

**Comment by sauleh** [comment]
Thanks so much!! 🙏

**Comment by armingh2000** [comment]
Not a problem. Anytime 😊

**Pull request merged**
